import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ReactFullpage from '@fullpage/react-fullpage';
import Fullpage from './fullpage';

export default function Home() {
  <ReactFullpage
  
  />
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fullpage/>
    </div>
  )
}
